// Generated by https://quicktype.io

export interface Job {
    _id:                 string;
    employer_name:       string;
    job_title:           string;
    job_description:     string;
    job_employment_type: string;
    job_apply_link:      string;
    job_latitude:        number;
    job_longitude:       number;
    Qualifications:      string[];
    Responsibilities:    string[];
    job_country:         string;
    job_city:            string;
    job_is_remote:       boolean;
    employer_logo:       null | string;
    __v:                 number;
}




